version: '3.3'
networks:
  e-cart:
    driver: 'bridge'
services:
  mongo:
    image: mongo:4
    restart: always
    volumes:
      - mongo:/data/db
    labels:
      - traefik.enable=false
    ports:
      - 27017:27017
    networks:
      - e-cart
volumes:
  mongo: {}
